export const GET_PRODUCTS_REQUESTED = 'GET_PRODUCTS_REQUESTED';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILED = 'GET_PRODUCTS_FAILED';

export const GET_PRODUCT_ID_REQUESTED = 'GET_PRODUCT_ID_REQUESTED';
export const GET_PRODUCT_ID_SUCCESS = 'GET_PRODUCT_ID_SUCCESS';
export const GET_PRODUCT_ID_FAILED = 'GET_PRODUCT_ID_FAILED';

export const USER_REGISTER_REQUESTED = 'USER_REGISTER_REQUESTED';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAILED = 'USER_REGISTER_FAILED';

export const USER_LOGIN_REQUESTED = 'USER_LOGIN_REQUESTED';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED';

export const LOGIN_STATUS_REQUESTED = 'LOGIN_STATUS_REQUESTED';
export const LOGIN_STATUS_SUCCESS = 'LOGIN_STATUS_SUCCESS';
export const LOGIN_STATUS_FAILED = 'LOGIN_STATUS_FAILED';

export const SET_LOGIN = 'SET_LOGIN';
export const SET_NAME = 'SET_NAME';
